version: 2

shared: &shared
    working_directory: ~/core.typed-dev
    steps:
      - checkout
      - run: java -version
      - run:
          command: |
            curl -O https://download.clojure.org/install/linux-install-1.9.0.397.sh
            chmod +x linux-install-1.9.0.397.sh
            sudo ./linux-install-1.9.0.397.sh
      - run: ./script/git/clone-all.sh
      - run: ./script/test-local

jobs:
  "openjdk-8":  
    <<: *shared
    docker:
      - image: circleci/openjdk:8u181-jdk

  "openjdk-9":
    <<: *shared
    docker:
      - image: circleci/openjdk:9-jdk

  "openjdk-10":
    <<: *shared
    docker:
      - image: circleci/openjdk:10-jdk

  "openjdk-11":
    <<: *shared
    docker:
      - image: circleci/openjdk:11-jdk

workflows:
  version: 2
  build:
    jobs:
      - "openjdk-8"
      - "openjdk-9"
      - "openjdk-10"
      - "openjdk-11"

#  nightly:
#    triggers:
#      - schedule:
#          cron: "0 6 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - "openjdk-8"
#      - "openjdk-9"
#      - "openjdk-10"
#      - "openjdk-11"
