#!/bin/sh

set -e

PROJECT=$1
# all but first
ARGS="${@:2}"

if [ -z $1 ]; then
  echo "Must specify project"
  exit 1
fi

cd $PROJECT
CLJ_CONFIG="../common" bash -c "./script/repl -A:local-deps $ARGS"
