#!/bin/sh

set -e

while read line
do
  NAME=`basename ${line}`
  while read line
  do
    cd $NAME
    CLJ=$line
    echo "PROJECT: $NAME (Clojure $CLJ)"
    if [ -e "script/test-local" ]; then
      ./script/test-local -J-Xmx2g -Sdeps "{:deps {org.clojure/clojure {:mvn/version \"$CLJ\"}}}"
    elif [ -e "script/test" ]; then
      ./script/test -J-Xmx2g -Sdeps "{:deps {org.clojure/clojure {:mvn/version \"$CLJ\"}}}"
    fi
    cd ..
  done < clojure-versions
done < projects
