#!/bin/sh

set -e

while read line
do
  NAME=`basename ${line}`
  while read line
  do
    cd $NAME
    CLJ=$line
    echo "PROJECT: $NAME (Clojure $CLJ)"
    CLJ_CONFIG="../common" bash -c "./script/test -A:local-deps -J-Xmx2g -Sdeps '{:deps {org.clojure/clojure {:mvn/version \"$CLJ\"}}}'" # -Stree
    cd ..
  done < clojure-versions
done < projects
